@startuml
class User{
- username: string
- password: string
+ CreateUser(username: string, password: string): void
+ CheckCredentials(username: string, password: string): bool
+ Login(): void
+ Logout(): void
}

class DeceasedPerson{
- name: string
- birthdate: DateTime
- deathdate: DateTime
- furtherInformation: string
- picture: Image
+ AddInformation(person: Person, information: string): void
+ DeleteInformation(person: Person, information: string): void

class NotificationManager{
+ SetReminderMemorialDay(date: DateTime): void
}
NotificationManager ---|> DeceasedPerson

class SearchManager{
+ SearchForDeceased(name: string): DeceasedPerson
}
SearchManager ---|> DeceasedPerson

class GraveStone{
+ CreateGraveStone(name: string, birthdate: DateTime, deathdate: DateTime): void
+ DeleteGraveStone(graveStone: GraveStone): void
}
GraveStone ---|> DeceasedPerson

class GraveCare{
- candle: Image
- flowers: Image
+ AddCandle(): void
+ RemoveCandle(): void
+ AddFlowers(): void
+ RemoveFlowers(): void
}

@enduml
